name: CI Check

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    check-vs2019:
        runs-on: windows-2019

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Check CMake configuration (VS2019)
              run: cmake --preset windows-x64-debug-2019 -Wno-dev --check-system-vars

            - name: Verify source files exist
              run: |
                  @(
                    "src/dllmain.cpp",
                    "src/includes.h",
                    "src/hooks/d3d12hook.cpp",
                    "src/hooks/d3d12hook.h",
                    "src/dev/Console.h",
                    "CMakeLists.txt",
                    "CMakePresets.json"
                  ) | ForEach-Object {
                    if (-not (Test-Path $_)) {
                      Write-Error "Missing file: $_"
                      exit 1
                    }
                  }

    check-vs2022:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Check CMake configuration (VS2022)
              run: cmake --preset windows-x64-debug-2022 -Wno-dev --check-system-vars
