name: CMake Build

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        strategy:
            matrix:
                config: [Release, Debug]
                arch: [x64, win32]

        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Configure CMake
              run: cmake --preset windows-${{ matrix.arch }}-${{ format('{0}', matrix.config) }}

            - name: Build
              run: cmake --build build/windows-${{ matrix.arch }}-${{ format('{0}', matrix.config) }} --config ${{ matrix.config }}

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: ImGui_DirectX12_Hook-${{ matrix.arch }}-${{ matrix.config }}
                  path: build/windows-${{ matrix.arch }}-${{ format('{0}', matrix.config) }}/${{ matrix.config }}/ImGui_DirectX12_Hook.dll
