name: CMake Build

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        strategy:
            matrix:
                config: [release-2019, debug-2019]
                arch: [x64]
                vs: [2019]

        runs-on: windows-2019

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Configure CMake
              run: cmake --preset windows-${{ matrix.arch }}-${{ matrix.config }}

            - name: Build
              run: cmake --build --preset windows-${{ matrix.arch }}-${{ matrix.config }}

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: ImGui_DirectX12_Hook-${{ matrix.arch }}-${{ matrix.config }}
                  path: build/windows-${{ matrix.arch }}-${{ matrix.config }}-2019/${{ contains(matrix.config, 'release') && 'Release' || 'Debug' }}/imgui_dx12_kiero_hook.dll

    build-2022:
        strategy:
            matrix:
                config: [release-2022, debug-2022]
                arch: [x64]
                vs: [2022]

        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Configure CMake
              run: cmake --preset windows-${{ matrix.arch }}-${{ matrix.config }}

            - name: Build
              run: cmake --build --preset windows-${{ matrix.arch }}-${{ matrix.config }}

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: ImGui_DirectX12_Hook-${{ matrix.arch }}-${{ matrix.config }}
                  path: build/windows-${{ matrix.arch }}-${{ matrix.config }}-2022/${{ contains(matrix.config, 'release') && 'Release' || 'Debug' }}/imgui_dx12_kiero_hook.dll
